
all:	example1  example2  

example1: example1_source.c
	gcc -o example1 example1_source.c -lpthread

example2: example2_source.c
	gcc -o example2 example2_source.c -lpthread


clean:
	rm -f example1 example2 example3 example4 

